### PR TITLE
22/09/2021 update

### PR DESCRIPTION
**Pull request by eiskye**

### CODE REVIEW

**Comment by MOURYAS2001** [comment]
yup  script did not working

**Comment by eiskye** [comment]
@MOURYAS2001 what problem are you having?

**Comment by MOURYAS2001** [comment]
> @MOURYAS2001 what problem are you having?

i cant use all thing like esp trigger and redear

**Comment by eiskye** [comment]
all feature are working. use the code updated or wait ekknod's accept the pull request.

**Comment by KirsebaerQAQ** [comment]
> 是的，脚本不起作用

I guess you did not follow the correct process at all or your obs did not capture csgo

**Comment by MOURYAS2001** [comment]
nop still nothing working even i can hear the sound when its activate but nothing work

**Pull request merged**
